config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get 'home/about_us', to: "home#about_us"
  get 'home/contact', to: "home#contact"
  get 'home/team', to: "home#team"
  get 'home/not_found', to: "home#not_found"

  devise_for :users
  # , controllers: {
  #   omniauth_callbacks: "users/omniauth_callbacks"
  # }



  resources :users, only: [:update, :show, :edit, :index] do
    resources :avatars, only: [:create]
    resources :user_pictures, only: [:create, :destroy]
    resources :comments, only: [:index, :create]
  end


  resources :correspondances, except: [:show, :edit, :new]
  
  resources :trips

  resources :conversations, only: [:index] do
    resources :messages, only: [:index, :create]
    resources :answers, only: [:new, :create]
    resources :trips, only: [:new, :create]
  end

  resources :flats, except: [:destroy, :index, :new] do
    resources :flat_pictures, only: [:create, :destroy]
  end
  
  resources :cities, only: [:show, :index]

  resources :user_preferences, only: [:create, :new]

  namespace :admins do
    resources :users, only: [:index, :update]
    resources :cities, except: [:show, :edit, :new, :destroy]
    resources :languages, except: [:show, :edit, :new]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :conversation
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :participant?, only: [:create, :index]
  before_action :in_a_correspondance?, only: [:create, :index]

  # GET /messages
  def index
    @conversation = Conversation.find(params[:conversation_id])
    @messages = Message.order(:created_at).where(conversation: @conversation)
    @other_user = @conversation.other_participant(current_user)
    ow = Rails.configuration.open_weather_api
    weather = ow.current id: @other_user.city.weather_id
    @icon = weather['weather'][0]['icon']
    @temp = (((weather['main']['temp'].to_f) - 273.15)*10).to_i.to_f / 10
    respond_to do |format|
      format.html{redirect_to root_path }
      format.js{}
    end
  end

  # POST /messages
  def create
    @conversation = Conversation.find(params[:conversation_id])
    @message = Message.new(user: current_user, conversation_id: params[:conversation_id], content: params[:content])
    respond_to do |format|
      if @message.save
        if @conversation.messages.size == 1
          current_user.update(token: current_user.token + 5)
        end
        format.html { redirect_to root_path }
        format.js {}
      else
        format.html { render root_path }
        format.js {}
      end
    end
  end


  private

  def participant?
    conversation = Conversation.find(params[:conversation_id])
    unless conversation.participants.include?(current_user) 
      flash[:danger] = "not possible to show messages because your are not participant to this conversation"
      redirect_to current_user
    end
  end
  def in_a_correspondance?
    conversation = Conversation.find(params[:conversation_id])
    user1 = conversation.author
    user2 = conversation.receiver
    if Correspondance.select(user1, user2)
      unless Correspondance.select(user1, user2).status == "validated"
        flash[:danger] = "not possible to show messages because the correspondance is not validated"
        redirect_to current_user
      end
    else
      flash[:danger] = "not possible to show messages because there is no correspondance"
      redirect_to current_user
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_create.html.erb
<div class="row  m-2">
    <div class="col-6 offset-6">
        <div class="row justify-content-end text-white">
        <blockquote class=" bg-primary rounded">
            <p class="text-muted text-center p-2"><%= @message.content %></p>
        </blockquote>
        </div>      
    </div>
</div>    

app/views/messages/_index.html.erb
<%  if @other_user %>
  <div class="boxed p-2 mb-1">
    <div class="row align-items-center justify-content-between">
      <div class="col-10">
        <div class="media align-items-center">
          <%if @other_user.avatar.attached?%>
            <%=image_tag(@other_user.avatar, :alt => "avatar", class: "avatar avatar-lg rounded mr-3")%>
          <%else%>
            <%= image_tag("img/user-1.jpg", :alt => "avatar", class: "avatar avatar-lg rounded mr-3") %>
          <%end%>
          <div class="media-body">
            <h5 class="mb-0"><%= @other_user.name %></h5>
            <%= link_to  @other_user do %>
              <span class="text-muted">View profile</span>
            <% end %>
            <div class="row align-items-center">
              <%= @other_user.city.name %>
              <div id="icon"><img id="wicon" src="http://openweathermap.org/img/w/<%=@icon%>.png" alt="Weather icon"></div>
              <%= @temp %> °C
            </div>
          </div>
        </div>
      </div>

      <div class="col-2 p-0">
      <%= link_to new_conversation_trip_path(@conversation), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal_trips', :class => "btn btn-rounded btn-ico btn-white"} do  %>
          <i class="fas fa-plane fa-lg text-primary mr-2"></i>
        <% end %>
        <%= link_to new_conversation_answer_path(@conversation),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal_answer', :class => "btn btn-rounded btn-ico btn-white"} do  %>
            <i class="fas fa-gamepad fa-lg text-primary"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div id="list_messages" class="bg-white" style="height: 30em;overflow: auto;">
    <% @messages.each do |message| %>
      <div class="row  m-2">
        <% user = message.user %>
        <% if user == @other_user %>
          <div class="col-6">
            <div class="row  text-black">
              <blockquote class="bg-light rounded">
                <p class="text-muted text-center p-2"><%= message.content %></p>
              </blockquote>
            </div>
          </div>
        <% else %>
          <div class="col-6 offset-6">
            <div class="row justify-content-end text-white">
              <blockquote class="bg-primary rounded">
                <p class="text-muted text-center p-2"><%= message.content %></p>
              </blockquote>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <br>
  <%= form_tag(conversation_messages_path(@conversation), method: "post", class: "form mb-5", id: "contact-form", remote: true)  do %>
      <div class="row">
        <div class="form-group col-10">
            <%= text_field_tag :content, nil, class: "form-control", placeholder: "Write a message" %>
        </div>
        <div class="text-center">
            <%= submit_tag("Send", class: "btn") %>
        </div>
      </div>
  <%end%>
<% else %>
<div class="boxed mb-5">
  <div class="container bg-white" style="height: 42em;">
  </div>
</div>
<% end %>

app/views/messages/create.js.erb
var listMessage = $('#list_messages');
listMessage.append("<%= j render 'create' %>");
$('#content').val('');
listMessage.scrollTop(listMessage.prop('scrollHeight'));

var conv = $('#conv<%=@conversation.id%>');
var text = $('#conv<%=@conversation.id%> .text-muted');
text.html("<%=@message.content[0..20] + "..."%>")
conv.detach().prependTo('#conversations')

app/views/messages/index.js.erb
var messages = $('#messages');
messages.html("<%= j render 'messages/index' %>");
var listMessage = $('#list_messages');
listMessage.scrollTop(listMessage.prop('scrollHeight'));
   