config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get 'home/about_us', to: "home#about_us"
  get 'home/contact', to: "home#contact"
  get 'home/team', to: "home#team"
  get 'home/not_found', to: "home#not_found"

  devise_for :users
  # , controllers: {
  #   omniauth_callbacks: "users/omniauth_callbacks"
  # }



  resources :users, only: [:update, :show, :edit, :index] do
    resources :avatars, only: [:create]
    resources :user_pictures, only: [:create, :destroy]
    resources :comments, only: [:index, :create]
  end


  resources :correspondances, except: [:show, :edit, :new]
  
  resources :trips

  resources :conversations, only: [:index] do
    resources :messages, only: [:index, :create]
    resources :answers, only: [:new, :create]
    resources :trips, only: [:new, :create]
  end

  resources :flats, except: [:destroy, :index, :new] do
    resources :flat_pictures, only: [:create, :destroy]
  end
  
  resources :cities, only: [:show, :index]

  resources :user_preferences, only: [:create, :new]

  namespace :admins do
    resources :users, only: [:index, :update]
    resources :cities, except: [:show, :edit, :new, :destroy]
    resources :languages, except: [:show, :edit, :new]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :author, class_name: "User"
  belongs_to :receiver, class_name: "User"
  validates :content, length: { in: 10..100 }
  validates :content, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correspondance_validated?, only: [:create]

  # GET /comments
  def index
    @user = User.find(params[:user_id])
    @sent_comments = current_user.authored_comments
    @received_comments = @user.received_comments
    respond_to do |format|
      format.html { redirect_to current_user}
      format.js {}
    end
  end

  # POST /comments
  def create
    content = params[:content]
    @comment = Comment.new(author: current_user, receiver: @other_user, content: content)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @other_user, notice: 'Comment was successfully created.' }
      else

        flash[:danger] =  'Comment was not created.'
        format.html { redirect_to @other_user }
      end
    end
  end


  private

  def correspondance_validated?
    @other_user = User.find(params[:user_id])
    c = Correspondance.select(current_user, @other_user)
    if c == false
      flash[:danger] = "not possible to leave comment if you are not in a correspondance"
      redirect_to current_user
    elsif c.status == "waiting"
      flash[:danger] = "You can not leave a comment if the correspondance is not validated"
      redirect_to current_user
    elsif c.status == "refused"
      flash[:danger] = "You can not leave a comment if the correspondance is refused"
      redirect_to current_user
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_index.html.erb
<div class="row justify-content-center">
	<div class="col-md-10 col-lg-8">
		<div class="mb-3">
			<h3>Comments received</h3>
			<% @received_comments.each do |c| %>
				<blockquote class="blockquote blockquote-2 boxed mb-1">
					<p><%= c.content %></p>
					<footer class="blockquote-footer">
						<div class="media align-items-center">
							<%= link_to user_path(c.author.id) do  %>
								<%=image_tag(c.author.avatar, :alt => "avatar", class: "avatar avatar-lg rounded mr-3")%>
								<%= c.author.name %>
							<% end %>
						</div>
					</footer>
				</blockquote>
			<% end %>
		</div>
		<% if @user.id == current_user.id %>
				<div class="mt-3">
					<h3>Comments given</h3>
					<% @user.authored_comments.each do |c| %>
						<div class="mb-2">
							<h3>
								<%= link_to user_path(c.receiver.id) do  %>
									<%=image_tag(c.receiver.avatar, :alt => "avatar", class: "avatar avatar-lg rounded mr-3")%>
									For <%= c.receiver.name %>
									<% end %>
							</h3>
							<blockquote class="blockquote blockquote-2 boxed">
								<p><%= c.content %></p>
							</blockquote>
						</div>
					<% end %>
				</div>
		<% end %>
	</div>
</div>

app/views/comments/_modal_create.html.erb
<div class="modal" tabindex="-1" role="dialog", id="modal_comments">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Leave a comment to <%= @user.name %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(model: @comment, url: user_comments_path(@user) , local: true) do |form| %>
          <div class="row">
            <div class="field col-10">
              <%= form.text_field :content, placeholder: "Write a comment", class: "form-control" %>
            </div>
            <%= button_tag(type: 'submit', class: "border-0 bg-white") do %>
              <i class="fas fa-paper-plane fa-2x  text-primary"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.js.erb
$("#tab").html("<%= escape_javascript(render 'comments/index') %>");