config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get 'home/about_us', to: "home#about_us"
  get 'home/contact', to: "home#contact"
  get 'home/team', to: "home#team"
  get 'home/not_found', to: "home#not_found"

  devise_for :users
  # , controllers: {
  #   omniauth_callbacks: "users/omniauth_callbacks"
  # }



  resources :users, only: [:update, :show, :edit, :index] do
    resources :avatars, only: [:create]
    resources :user_pictures, only: [:create, :destroy]
    resources :comments, only: [:index, :create]
  end


  resources :correspondances, except: [:show, :edit, :new]
  
  resources :trips

  resources :conversations, only: [:index] do
    resources :messages, only: [:index, :create]
    resources :answers, only: [:new, :create]
    resources :trips, only: [:new, :create]
  end

  resources :flats, except: [:destroy, :index, :new] do
    resources :flat_pictures, only: [:create, :destroy]
  end
  
  resources :cities, only: [:show, :index]

  resources :user_preferences, only: [:create, :new]

  namespace :admins do
    resources :users, only: [:index, :update]
    resources :cities, except: [:show, :edit, :new, :destroy]
    resources :languages, except: [:show, :edit, :new]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flat.rb
class Flat < ApplicationRecord
  before_validation :default_values
  belongs_to :user
  has_many_attached :pictures
  validates :room, inclusion: { in: ["Bed-room", "Living-room", ""], message: "%{value} is not a valid room"}
  validates :sleep, inclusion: { in: ["Couch", "Bed",""], message: "%{value} is not a valid sleep"}
  validates :place, numericality: { greater_than: 0, less_than: 4 }

  def default_values
    self.room ||= ''
    self.sleep ||= ''
    self.place ||= 1
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_flat, only: [:show, :edit, :update]

  # GET /flats/1
  def show
    @flat = Flat.find(params[:id])
    respond_to do |format|
      format.html { redirect_to current_user}
      format.js {}
    end
  end


  # GET /flats/1/edit
  def edit
    @flat = current_user.flat
    respond_to do |format|
      format.html { redirect_to current_user}
      format.js {}
    end
  end

  # POST /flats
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to current_user, notice: 'Flat was successfully updated.' }
      else
        format.html { redirect_to :current_user }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:user_id, :address, :description, :room, :sleep, :place)
    end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_edit.html.erb
<div class="row justify-content-center">
	<div class="col-md-10 col-lg-8">
    <h4 class="mb-2 fs-20 font-weight-normal">General Information</h4>
    <%= form_with(model: @flat, local: true) do |form| %>
      <% if @flat.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h2>
          <ul>
          <% @flat.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address, class: "form-control mb-2" %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control mb-2" %>
      </div>
      
      <div class="form-row mb-3">
        <div class="col">
          <div class="field">
            <label for="flatRoom">Type of accomodation</label><br>
            <%= form.radio_button :room, 'Bed-room' %> Bed-room <br>
            <%= form.radio_button :room, 'Living-room' %> Living-room <br>
          </div>
        </div>
        <div class="col">
          <div class="field">
            <label for="flatSleep">Sleeping place</label> <br>
            <%= form.radio_button :sleep, 'Bed' %> Bed <br>
            <%= form.radio_button :sleep, 'Couch' %> Couch <br>
          </div>
        </div>
        <div class="col">
          <div class="field">
            <label for="flatPlace">Number of availible place </label> <br>
            <%= form.number_field :place, within: 1..3 %>
          </div>
        </div>
        
      </div>        

      <div class="actions">
        <%= form.submit "Save changes", class: "btn btn-secondary mb-5" %>
      </div>
      <hr>
    <% end %>
    
    <h4 class="mb-2 fs-20 font-weight-normal">Pictures Information</h4>
    <p><%= label_tag "Delete pictures" %></p> 
    <div class="row ">
      <% @flat.pictures.each do |pic| %>
        <div class="col-md-4">
          <figure>
            <%=image_tag(pic, :alt => "picture")%>
            <figcaption class="user-caption">
              <%= link_to 'Delete', flat_flat_picture_path(@flat,:pic => pic), :method => :delete, :data => {:confirm => 'Are you sure?'}, class: "btn btn-secondary m-auto"  %>
            </figcaption>
          </figure>
        </div>
      <%end%>
    </div>

    <%= form_tag flat_flat_pictures_path(@flat), multipart: true do %>
      <p><%= label_tag "Add a new picture" %></p> 
      <%= file_field_tag :pictures %> <br><br>
      <%= submit_tag "Upload picture", class: "btn btn-secondary mb-5" %>
    <% end %>
  </div>
</div>

app/views/flats/_show.html.erb
<div class="container col-9">
  <div class="container pr-5 pl-5">
    <div class="row gutter-2 gutter-lg-4">
      <div class="col-md-6 col-lg-4">
        <div class="media align-items-center mb-2">
          <i class="fas text-primary fa-2x mr-3 fa-users"></i>
          <h5 class="fs-25 font-weight-bold"><%= @flat.place %> place(s)</h5>
        </div>
      </div>
      <div class="col-md-6 col-lg-4">
        <div class="media align-items-center mb-2">
          <i class="fas text-primary fa-2x mr-3 fa-bed"></i>
            <h5 class="fs-25 font-weight-bold"><%= @flat.sleep %></h5>
        </div>
      </div>
      <div class="col-md-6 col-lg-4">
        <div class="media align-items-center mb-2">
          <i class="fas text-primary fa-2x mr-3 fa-home"></i>
            <h5 class="fs-25 font-weight-bold"><%= @flat.room %></h5>
        </div>
      </div>
    </div>
  </div>

    <div class="container">
      <label>Pictures</label> 
      <div class="row mb-2 ">
        <div class="col">
          <article class="card">
            <div class="card-body overflow-hidden">
              <%if @flat.pictures.attached?%>
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <div class="row">
                        <%= image_tag @flat.pictures[0], :alt => "Image", style: "width: 100%;"%>
                      </div>
                    </div>
                    <%(1...@flat.pictures.count).each do |pic|%>
                      <div class="carousel-item">
                        <%= image_tag @flat.pictures[pic], :alt => "Image", style: "width: 100%;"  %>
                      </div>
                    <% end %>  
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
              <% end %>
            </div>
          </article>
        </div>
      </div>
    </div>
  

  <div class="container"> 
    <label>Description</label> 
  	<article class="card"> 
      <div class="mb-1 mt-1 p-2">
        <%= @flat.description %>
      </div>
    </article>
  </div>
</div>
  <!-- / post -->

app/views/flats/edit.js.erb
$("#tab").html("<%= escape_javascript(render 'flats/edit') %>");

app/views/flats/show.js.erb
$("#tab").html("<%= escape_javascript(render 'flats/show') %>");