config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  get 'home/about_us', to: "home#about_us"
  get 'home/contact', to: "home#contact"
  get 'home/team', to: "home#team"
  get 'home/not_found', to: "home#not_found"

  devise_for :users
  # , controllers: {
  #   omniauth_callbacks: "users/omniauth_callbacks"
  # }



  resources :users, only: [:update, :show, :edit, :index] do
    resources :avatars, only: [:create]
    resources :user_pictures, only: [:create, :destroy]
    resources :comments, only: [:index, :create]
  end


  resources :correspondances, except: [:show, :edit, :new]
  
  resources :trips

  resources :conversations, only: [:index] do
    resources :messages, only: [:index, :create]
    resources :answers, only: [:new, :create]
    resources :trips, only: [:new, :create]
  end

  resources :flats, except: [:destroy, :index, :new] do
    resources :flat_pictures, only: [:create, :destroy]
  end
  
  resources :cities, only: [:show, :index]

  resources :user_preferences, only: [:create, :new]

  namespace :admins do
    resources :users, only: [:index, :update]
    resources :cities, except: [:show, :edit, :new, :destroy]
    resources :languages, except: [:show, :edit, :new]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :random_user

  def index
    @cities = City.all.slice(0...8)
    @random_cities = City.all.sample
    random_user

  end

  def about_us
  end

  def contact
  end

  def team
  end

  def not_found
    render "404"
  end

  private

  def random_user

    @users = User.all
    rand_users = []
    @user_matched = []
    @users.each do |user|
      if user != current_user
        if user.matchmaking(current_user) > 2
          rand_users << user
        end
      end
    end

    if rand_users.size < 8
      @user_matched += rand_users
    else
      8.times do
        @user_matched << rand_users.sample
      end
    end

    return @user_matched
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/404.html.erb
<div class="viewport">
      <div class="image image-overlay image-blur" style="background-image:url('<%=asset_path("cities/amsterdam.jpg")%>">
      </div>
      <div class="container">
        <div class="row justify-content-center align-items-center vh-100">
          <div class="col-md-6 col-lg-4 text-white text-center">
            <h1>Page Under Construction</h1>
            <p>The page you were looking for is under construction.<p>
          </div>
        </div>
      </div>
    </div>

app/views/home/_carousel.html.erb
  <!-- profil carousel -->
         <section class="bg-light">
         <div class="row justify-content-center">
          <div class="col-md-6 text-center">
            <span class="eyebrow d-block mb-1 text-primary">Meet Him</span>
          </div>
        </div>
    <section class="section-decorated-bottom pt-0">
      <div class="decorated-bottom text-light">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 40"  preserveAspectRatio="none">
          <path d="">
            <animate
              attributeName="d"
              begin="0s"
              dur="5s"
              repeatCount="indefinite"
              values="
              M0,0 C200,7.11236625e-15 200,40 400,40 C600,40 800,0 1000,0 L1000,50 L0,50 L0,0 Z;
              M0,40 C200,40 400,0 600,0 C800,0 800,40 1000,40 L1000,50 L0,50 L0,40 Z;
              M0,30 C200,30 200,0 400,0 C600,0 800,40 1000,40 L1000,50 L0,50 L0,30 Z;
              M0,0 C200,7.11236625e-15 200,40 400,40 C600,40 800,0 1000,0 L1000,50 L0,50 L0,0 Z;"></animate>
          </path>
        </svg>
      </div>
      <div class="container-fluid" style="max-width:650px">

        <div class="row" data-aos="fade-left" data-aos-delay="500">
          <div class="col">
            <div class="owl-carousel visible" data-items="[3,2,1]" data-margin="20" data-dots="true" data-loop="true" data-center="true">
            <% @user_matched.each do |user| %>
              <article class="tile tile-long">
                <div class="tile-image" style="background-image: url(<%= rails_blob_url(user.avatar)%>)"></div>
                <a href="" class="tile-content">
                  <div class="tile-header on-hover text-right">
                     <img src="../assets/flag/italie.png" alt="flag">
                  </div>
                  <div class="tile-footer">
                    <div class="fixed-bottom text-center">
                      <span class="eyebrow"><%= user.first_name %> <%= user.last_name %></span>
                      <h6><%= user.city.name %>, <%= user.city.country %></h6>
                    </div>
                  </div>
                </a>
              </article>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- / profil carousel -->

app/views/home/_partial_3_col.html.erb
stylesheet_link_tag "home"
<div class="row gutter-0">
  <div class="col-md-4">
    <div class="bordered rising text-center">
    <i class="fas fa-user-friends"></i>
      <h2>Find a mate</h2>
    </div>
  </div>
  <div class="col-md-4">
    <div class="bordered rising text-center">
    <h2>Chat a bit</h2>
    </div>
  </div>
  <div class="col-md-4">
    <div class="bordered rising text-center">
    <h2>Go discover the world</h2>
    </div>
  </div>
</div>

app/views/home/about_us.html.erb
  <!-- features -->
    <section class="bg-primary separator-top separator-bottom">
      <div class="container">
        <div class="row">
          <div class="col text-white">
            <h2>Our <b>Services</b></h2>
          </div>
        </div>
        <div class="row gutter-2 gutter-lg-4 bg-blue">
          <div class="col-md-6 col-lg-4">
            <div class="media align-items-center mb-2">
              <i class="svg-icon fs-50 text-pink mr-3">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                   width="64px" height="64px" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve">
                <path fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" d="M32,1c14.359,0,27,12.641,27,27S46.359,55,32,55
                  c-10,0-13-4-13-4"/>
                <circle fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" cx="32" cy="28" r="20"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="32" y1="54" x2="32" y2="64"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="22" y1="63" x2="42" y2="63"/>
                </svg>
              </i>
              <div class="media-body">
                <h5 class="fs-20 font-weight-normal text-white">+ 30 cities across Europe</h5>
              </div>
            </div>
            <p class="text-light">Live the experience differently with Mif, travel across Europe at a lower cost by living with locals and discovering the city as a local with your correspondent</p>
          </div>
          <div class="col-md-6 col-lg-4">
            <div class="media align-items-center mb-2">
              <i class="svg-icon fs-50 text-pink mr-3">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                   width="64px" height="64px" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve">
                <polyline fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" points="32,12 32,32 41,41 "/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="4" y1="32" x2="8" y2="32"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="56" y1="32" x2="60" y2="32"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="32" y1="60" x2="32" y2="56"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="32" y1="8" x2="32" y2="4"/>
                <path fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" d="M32,63C14.879,63,1,49.121,1,32S14.879,1,32,1"/>
                <path fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" d="M32,63c17.121,0,31-13.879,31-31
                  c0-6.713-2.134-12.926-5.759-18l-5.62-5.621"/>
                <polyline fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="bevel" stroke-miterlimit="10" points="51,19 51,8 62,8 
                  "/>
                </svg>
              </i>
              <div class="media-body">
                <h5 class="fs-20 font-weight-normal text-white">24/7 availability</h5>
              </div>
            </div>
            <p class="text-light">Many miffer around the world present on our platform and organizing trips every day</p>
          </div>
          <div class="col-md-6 col-lg-4">
            <div class="media align-items-center mb-2">
              <i class="svg-icon fs-50 text-pink mr-3">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                   width="64px" height="64px" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve">
                <path fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" d="M50,27H14C6.82,27,1,32.82,1,40s5.82,13,13,13
                  c4.6,0,8.632-2.396,10.943-6h14.113C41.368,50.604,45.4,53,50,53c7.18,0,13-5.82,13-13S57.18,27,50,27z"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="bevel" stroke-miterlimit="10" x1="14" y1="32" x2="14" y2="48"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="bevel" stroke-miterlimit="10" x1="22" y1="40" x2="6" y2="40"/>
                <circle fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="bevel" stroke-miterlimit="10" cx="50" cy="39.99" r="7"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="bevel" stroke-miterlimit="10" x1="50" y1="33" x2="50" y2="47"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="bevel" stroke-miterlimit="10" x1="57" y1="40" x2="43" y2="40"/>
                <polyline fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" points="32,27 32,21 46,21 46,14 36,14 36,11 "/>
                </svg>
              </i>
              <div class="media-body">
                <h5 class="fs-20 font-weight-normal text-white">In the heart of the city</h5>
              </div>
            </div>
            <p class="text-light"> Many cities organize weekly language exchanges, miffer parties and various activities, all to allow our members to have an unforgettable stay and to make new friends</p>
          </div>
          <div class="col-md-6 col-lg-4">
            <div class="media align-items-center mb-2">
              <i class="svg-icon fs-50 text-pink mr-3">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                   width="64px" height="64px" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve">
                <circle fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" cx="32" cy="32" r="31"/>
                <circle fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" cx="32" cy="32" r="15"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="26" y1="18" x2="26" y2="1"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="38" y1="18" x2="38" y2="1"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="26" y1="63" x2="26" y2="46"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="38" y1="63" x2="38" y2="46"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="46" y1="26" x2="63" y2="26"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="46" y1="38" x2="63" y2="38"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="1" y1="26" x2="18" y2="26"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="1" y1="38" x2="18" y2="38"/>
                </svg>
              </i>
              <div class="media-body">
                <h5 class="fs-20 font-weight-normal text-white">Get to know our miffer</h5>
              </div>
            </div>
            <p class="text-light">You can meet many miffer on our platform and discuss with them through our messaging</p>
          </div>
          <div class="col-md-6 col-lg-4">
            <div class="media align-items-center mb-2">
              <i class="svg-icon fs-50 text-pink mr-3">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                   width="64px" height="64px" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve">
                <g>
                  <rect x="1" y="1" fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" width="62" height="62"/>
                </g>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="18" y1="8" x2="18" y2="28"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="28" y1="18" x2="8" y2="18"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="56" y1="18" x2="36" y2="18"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="10" y1="54" x2="26" y2="38"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="10" y1="38" x2="26" y2="54"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="36" y1="43" x2="56" y2="43"/>
                <line fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" x1="36" y1="49" x2="56" y2="49"/>
                </svg>
              </i>
              <div class="media-body">
                <h5 class="fs-20 font-weight-normal text-white">up to 50 members</h5>
              </div>
            </div>
            <p class="text-light">Already over 50 members have joined our community</p>
          </div>
          <div class="col-md-6 col-lg-4">
            <div class="media align-items-center mb-2">
              <i class="svg-icon fs-50 text-pink mr-3">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                   width="64px" height="64px" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve">
                <polygon fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" points="63,18 63,54 1,54 1,10 22,10 30,18 "/>
                </svg>
              </i>
              <div class="media-body">
                <h5 class="fs-20 font-weight-normal text-white">Become a host</h5>
              </div>
            </div>
            <p class="text-light">discover his culture and learn a language with him</p>
          </div>
        </div>
      </div>
    </section>
    <!-- / features -->

    


    



   

app/views/home/contact.html.erb
 <section class="bg-white">
      <div class="container">
      <div class="image image-overlay image-zoom" style="background-image:url('<%=asset_path("img/4FriendsTopCity2.jpg")%>')"></div>
        <div class="row">
          <div class="col-md-6">
          <span class="eyebrow mb-1 "><h4>Get in touch with us</h4></span>
            <h2 class="text-white">We’ll get back to you as soon as possible.</h2>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <form>
              <div class="form-row mb-1">
                <div class="col">
                  <input type="text" class="form-control form-control-minimal" placeholder="Name">
                </div>
                <div class="col">
                  <input type="text" class="form-control form-control-minimal" placeholder="Mail">
                </div>
                <div class="col">
                  <input type="text" class="form-control form-control-minimal" placeholder="Phone">
                </div>
              </div>
              <div class="form-row mb-1">
                <div class="col">
                  <textarea class="form-control form-control-minimal" id="exampleFormControlTextarea1" rows="3" placeholder="Your Message"></textarea>
                </div>
              </div>
              <div class="form-row mt-3">
                <div class="col">
                  <button class="btn btn-primary px-5">Send Mail</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

app/views/home/index.html.erb
    <!-- cover -->
    <section class="p-0 mb-0">
      <div class="swiper-container text-white"
        data-top-top="transform: translateY(0px);"
        data-top-bottom="transform: translateY(250px);">
        <div class="swiper-wrapper">
          <div class="swiper-slide vh-100">
            <div class="image image-overlay image-zoom" style="background-image:url('<%=asset_path("img/4FriendsTopCity3.jpg")%>')"></div>
            <div class="caption" data-aos="fade-up">
              <div class="container justify-content-center">
                <div class="row align-items-center vh-100">
                  <div class="col-lg-8" data-swiper-parallax-y="-100%">
                  <br><br><br><br><br><br><br><br><br><br>
                    <h1 class="display-4" >Travel differently in <br><i class="font-weight-bold" id="typed"></i></h1>
                    <div id="typed-strings">
                      <% @cities.each do |city| %>
                        <p><%= city.name %>.</p>
                      <% end %>
                    </div>
                    <% if user_signed_in? %>
                      <%= link_to "Welcome #{current_user.first_name}", user_path(current_user.id), class: "btn btn-primary btn-rounded px-3" %>
                    <% else %>
                      <%= link_to "Come Aboard, It's free", new_user_session_path, class: "btn btn-primary btn-rounded px-3" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="swiper-footer mb-5">
            <div class="container-fluid">
              <div class="row">
                <div class="col text-center">
                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
     <!-- cover -->

     <!-- presentation -->
    <section class="section-lg bg-gray">
      <div class="container">
        <div class="row text-center text-lg-left text-white">
          <div class="col-12 col-lg-9" style="max-width: 910px;">
            <div class="row">
              <div class="col-lg-8 text-black">
                <h2 class="text-black">For us, discovering a culture with a local is <b class="text-black">the best experience ever!</b></h2>
              </div>
            </div>
            <div class="row gutter-0 bg-cyan">
              <div class="col-sm-6 col-lg-4" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom">
                <div class="bordered rising p-3">
                <i class="fas fa-user-friends fa-4x text-pink"></i>
                  <h4 class="mb-0">Friends</h4>
                  <p>Match with people from other cities with common interests.</p>
                </div>
              </div>
              <div class="col-sm-6 col-lg-4" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom" data-aos-delay="150">
                <div class="bordered rising p-3">
                   <i class="fas fa-comments fa-4x text-pink"></i>
                  <h4 class="mb-0">Chat</h4>
                  <p>Talk with him, get friend and plan an exchange</p>
                </div>
              </div>
               <div class="col-sm-6 col-lg-4" data-aos="fade-up" data-aos-anchor-placement="bottom-bottom" data-aos-delay="300">
                <div class="bordered rising p-3">
                  <i class="fas fa-plane-departure fa-4x text-pink"></i>
                  <h4 class="mb-0">Travel</h4>
                  <p>Welcome him to your home and visit him !</p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 col-lg-3 presentation presentation-responsive">
            <%=image_tag("img/miffer.png", :alt => "Image", class: "left-25 vertical-align")%>
          </div>
        </div>
      </div>
    </section>
    <!-- / presentation -->

    <!-- destination carroussel -->

     <section class="bg-light">

      <div class="row justify-content-center">
         <div class="container gallery">
        <div class="row justify-content-center">
          <div class="col-md-6 text-center">
            <h2><b>Discover</b> our cities.</h2>
            <p>Select the city of your dreams and discover all the miffers who live there.</p>
          </div>
        </div>
        <ul class="masonry row gutter-2">
              <% @cities.each do |city|%>
              <li class="col-md-6 col-lg-3">
                <% if city.name == "Paris" %>
                  <article class="tile">
                <% end %>
                <% if city.id.even? %>
                  <article class="tile tile-long">
                <% else %>
                  <% if city.id % 5 == 0 %>
                    <article class="tile tile-long">
                  <% end %>
                  <article class="tile">
                <% end %>
                  <div class="tile-image" style="background-image: url(<%=rails_blob_url(city.picture)%>);"></div>
                    <%= link_to city_path(city) do%>
                    <div class="tile-header">
                      <h2 class="text-white" style="text-align: center"><%= city.name %></h2>
                      <h4 class="text-white" style="text-align: center"><strong><%= city.users.count %> miffers </strong></h4>
                    </div>
                    <% end %>
                </article>
              </li>
              <% end %>
            </ul>
            <div class="row">
          <div class="col text-center">
            <%= link_to cities_path, class:"btn btn-rounded btn-with-ico btn-primary" do %>
               View All Cities <i class="fas fa-chevron-right fs-24"></i>
            <%end%>
          </div>
        </div>
          </div>
        </div>
      </div>
    </section>
    <!-- / destination carrousel -->

     <!-- testimonials -->
    <section class="bg-orange text-white separator-top">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 text-center">
            <h2><b>Testimony</b></h2>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-md-8">
            <div class="owl-carousel visible accent" data-dots="true" data-loop="true" data-margin="100" data-autoplay="true">
              <blockquote class="blockquote blockquote-1">
                <p>This site is magic I met my best friend thanks to Mif.</p>
                <footer class="blockquote-footer">
                  <div class="media align-items-center">
                    <%=image_tag("img/avatar/jean.png", :alt => "Avatar", class: "avatar user-rounded")%>
                    <div class="media-body ml-2">
                      <span class="d-block mb-0 text-white">Jean Tirard</span>
                      <small class="text-primary">Entrepreneur</small>
                    </div>
                  </div>
                </footer>
              </blockquote>
              <blockquote class="blockquote blockquote-1">
                <p>Very good experience I had a great weekend in Budapest with my correspondent.</p>
                <footer class="blockquote-footer">
                  <div class="media align-items-center">
                    <%=image_tag("img/avatar/flo.png", :alt => "Avatar", class: "avatar user-rounded")%>
                    <div class="media-body ml-2">
                      <span class="d-block mb-0 text-white">Florent Bilocq</span>
                      <small class="text-primary">Web Develloper</small>
                    </div>
                  </div>
                </footer>
              </blockquote>
              <blockquote class="blockquote blockquote-1">
                <p>Great to meet girls.</p>
                <footer class="blockquote-footer">
                  <div class="media align-items-center">
                    <%=image_tag("img/avatar/thom.png", :alt => "Avatar", class: "avatar user-rounded")%>
                    <div class="media-body ml-2">
                      <span class="d-block mb-0 text-white">Thomas Feral</span>
                      <small class="text-primary">Ingenieur</small>
                    </div>
                  </div>
                </footer>
              </blockquote>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- / testimonial -->


    <!-- presentation -->
    <section class="bg-light">
      <div class="container">
        <div class="row align-items-center justify-content-center presentation-container">
          <div class="col-8 col-md-6 col-lg-4" data-aos="zoom-in">
            <div class="presentation-circle">
              <figure style="background-image: url(<%=asset_path('cities/prague.jpg')%>"></figure>
            </div>
          </div>
          <div class="col-lg-5 col-md-6 pl-md-7 text-center text-md-left">
            <span class="eyebrow text-primary mb-1">Special for you</span>
            <h3 class="h2">Amazing Trip</h3>
            <p>Get your head filled with incredible memories of something you are not going to see everyday.</p>
          </div>
        </div>
        <div class="row align-items-center justify-content-center presentation-container">
          <div class="col-md-6 col-lg-5 pr-md-7 text-center text-md-right">
            <span class="eyebrow text-primary mb-1">Special for you</span>
            <h3 class="h2">Friends For Life</h3>
            <p>Every memories are better to be shared with someone you like, right ?</p>
          </div>
          <div class="col-8 col-md-6 col-lg-4" data-aos="zoom-in">
            <div class="presentation-circle with-delay">
              <figure style="background-image: url(<%=asset_path('img/picnic.jpg')%>"></figure>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- / presentation -->

    <!-- featured carousel -->
    <section class="bg-light pb-0">
        <div class="row" data-aos="fade-up">
          <div class="col">
            <div class="gallery">
              <div class="gallery-container">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <div class="image image-zoom image-overlay-dark" style="background-image:url(<%=asset_path('img/picnic.jpg')%>">
                    </div>
                    <div class="caption text-white" data-swiper-parallax="-100%">
                      <div class="container">
                        <div class="row align-items-center justify-content-center vh-50">
                          <div class="col text-center">
                            <span class="eyebrow">Join The Community</span>
                            <h1 class="display-3">The miffers are waiting for you.</h1>
                            <%= link_to "Sign Up",new_user_registration_path, class: "btn btn-outline-white btn-rounded"  %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="image image-overlay-dark image-scrolling" style="background-image:url(<%=asset_path('cities/amsterdam.jpg')%>)"
                    data--100-bottom-top="transform: translateY(0%);"
                    data-top-bottom="transform: translateY(25%);">
                    </div>
                    <div class="caption text-white" data-swiper-parallax="-100%">
                      <div class="container">
                        <div class="row align-items-center vh-75">
                          <div class="col-md-8 col-lg-6">
                            <span class="eyebrow">Travel</span>
                            <h1 class="display-3 mb-1">Discover Europe</h1>
                            <p>Stay with locals and meet other travelers Live a authentic experience</p>
                            <%= link_to "Go", cities_path, class: "btn btn-white btn-rounded mt-2 px-5"  %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="swiper-slide">
                    <div class="image image-overlay-dark image-scrolling" style="background-image:url(<%=asset_path('img/PicNicNewYork.jpg')%>)"
                    data--100-bottom-top="transform: translateY(0%);"
                    data-top-bottom="transform: translateY(25%);">
                    </div>
                    <div class="container">
        <div class="row justify-content-center align-items-center">
          <div class="col-md-8 col-lg-6 text-center text-white text-shadow">
            <span class="eyebrow mb-1">More Questions ?</span>
            <h2 class="display-4">Ask our <b>live support</b> via chat or phone</h2>
              <%= link_to "Contact", "/home/contact", class: "btn btn-white btn-rounded px-4" %>
          </div>
        </div>
      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="gallery-thumbs">
                <div class="swiper-wrapper">
                  <div class="swiper-slide">
                    <h5>Joins Us</h5>
                  </div>
                  <div class="swiper-slide">
                    <h5>Go On An Adventure</h5>
                  </div>
                  <div class="swiper-slide">
                    <h5>Ask Your Question</h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>
    <!-- / featured carousel -->